name: GreenGate CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Client Image
        uses: docker/build-push-action@v5
        with:
          context: ./Client
          file: docker/prod/Dockerfile.client.prod
          push: true
          tags: |
            sandunsanjeewa/greengate-client:latest
            sandunsanjeewa/greengate-client:${{ github.sha }}

      - name: Build & Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: docker/prod/Dockerfile.server.prod
          push: true
          tags: |
            sandunsanjeewa/greengate-server:latest
            sandunsanjeewa/greengate-server:${{ github.sha }}

      - name: Build & Push Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/prod/Dockerfile.nginx.prod
          push: true
          tags: |
            sandunsanjeewa/greengate-nginx:latest
            sandunsanjeewa/greengate-nginx:${{ github.sha }}

  deploy:
   name: Deploy to EC2
   needs: build
   runs-on: ubuntu-latest

   steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
         echo "Deploying GreenGate on EC2..."
         cd /home/ubuntu/greengate
         docker-compose -f docker-compose.prod.yml pull
         docker-compose -f docker-compose.prod.yml up -d
         docker image prune -f
         echo "Deployment finished."
         

      